# plyj_lextab.py. This file automatically created by PLY (version 3.8). Don't edit!
_tabversion   = '3.8'
_lextokens    = {'GTEQ', 'CLASS', 'INSTANCEOF', 'FLOAT', 'SWITCH', 'NAME', 'VOLATILE', 'XOR_ASSIGN', 'BREAK', 'BODY', 'TRY', 'OR_ASSIGN', 'MINUSMINUS', 'LSHIFT_ASSIGN', 'INTERFACE', 'WHILE', 'FALSE', 'NUM', 'ELSE', 'PROTECTED', 'THROW', 'MINUS_ASSIGN', 'FINAL', 'STRING_LITERAL', 'NATIVE', 'VOID', 'THIS', 'ASSERT', 'RSHIFT_ASSIGN', 'CHAR', 'STRICTFP', 'STATIC', 'NEQ', 'RRSHIFT_ASSIGN', 'CASE', 'PRIVATE', 'PUBLIC', 'SYNCHRONIZED', 'RSHIFT', 'DO', 'TRUE', 'SHORT', 'FINALLY', 'NEW', 'THROWS', 'LONG', 'IMPORT', 'IMPLEMENTS', 'PLUS_ASSIGN', 'ELLIPSIS', 'PACKAGE', 'IF', 'RETURN', 'AND', 'RRSHIFT', 'FOR', 'PLUSPLUS', 'CONTINUE', 'ABSTRACT', 'CHAR_LITERAL', 'SUPER', 'OR', 'TIMES_ASSIGN', 'BLOCK_COMMENT', 'AND_ASSIGN', 'BOOLEAN', 'DEFAULT', 'INT', 'TRANSIENT', 'EQ', 'REMAINDER_ASSIGN', 'LTEQ', 'CATCH', 'BYTE', 'NULL', 'LINE_COMMENT', 'LSHIFT', 'EXTENDS', 'ENUM', 'DOUBLE', 'DIVIDE_ASSIGN'}
_lexreflags   = 0
_lexliterals  = '()+-*/=?:,.^|&~!=[]{};<>@%'
_lexstateinfo = {'INITIAL': 'inclusive', 'java8': 'exclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NAME>[A-Za-z_$][A-Za-z0-9_$]*)|(?P<t_ANY_newline>\\n+)|(?P<t_ANY_newline2>(\\r\\n)+)|(?P<t_OPEN_BRACE>\\{)|(?P<t_ANY_BLOCK_COMMENT>/\\*(.|\\n)*?\\*/)|(?P<t_ANY_LINE_COMMENT>//.*)|(?P<t_NUM>\\.?[0-9][0-9eE_lLdDa-fA-F.xXpP]*)|(?P<t_CHAR_LITERAL>\\\'([^\\\\\\n]|(\\\\.))*?\\\')|(?P<t_STRING_LITERAL>\\"([^\\\\\\n]|(\\\\.))*?\\")|(?P<t_ELLIPSIS>\\.\\.\\.)|(?P<t_RRSHIFT_ASSIGN>>>>=)|(?P<t_MINUSMINUS>\\-\\-)|(?P<t_OR>\\|\\|)|(?P<t_PLUSPLUS>\\+\\+)|(?P<t_PLUS_ASSIGN>\\+=)|(?P<t_RSHIFT_ASSIGN>>>=)|(?P<t_OR_ASSIGN>\\|=)|(?P<t_XOR_ASSIGN>\\^=)|(?P<t_LSHIFT_ASSIGN><<=)|(?P<t_RRSHIFT>>>>)|(?P<t_TIMES_ASSIGN>\\*=)|(?P<t_LSHIFT><<)|(?P<t_REMAINDER_ASSIGN>%=)|(?P<t_DIVIDE_ASSIGN>/=)|(?P<t_EQ>==)|(?P<t_LTEQ><=)|(?P<t_MINUS_ASSIGN>-=)|(?P<t_RSHIFT>>>)|(?P<t_NEQ>!=)|(?P<t_GTEQ>>=)|(?P<t_AND>&&)|(?P<t_AND_ASSIGN>&=)', [None, ('t_NAME', 'NAME'), ('t_ANY_newline', 'newline'), ('t_ANY_newline2', 'newline2'), None, ('t_OPEN_BRACE', 'OPEN_BRACE'), ('t_ANY_BLOCK_COMMENT', 'BLOCK_COMMENT'), None, ('t_ANY_LINE_COMMENT', 'LINE_COMMENT'), (None, 'NUM'), (None, 'CHAR_LITERAL'), None, None, (None, 'STRING_LITERAL'), None, None, (None, 'ELLIPSIS'), (None, 'RRSHIFT_ASSIGN'), (None, 'MINUSMINUS'), (None, 'OR'), (None, 'PLUSPLUS'), (None, 'PLUS_ASSIGN'), (None, 'RSHIFT_ASSIGN'), (None, 'OR_ASSIGN'), (None, 'XOR_ASSIGN'), (None, 'LSHIFT_ASSIGN'), (None, 'RRSHIFT'), (None, 'TIMES_ASSIGN'), (None, 'LSHIFT'), (None, 'REMAINDER_ASSIGN'), (None, 'DIVIDE_ASSIGN'), (None, 'EQ'), (None, 'LTEQ'), (None, 'MINUS_ASSIGN'), (None, 'RSHIFT'), (None, 'NEQ'), (None, 'GTEQ'), (None, 'AND'), (None, 'AND_ASSIGN')])], 'java8': [('(?P<t_ANY_newline>\\n+)|(?P<t_ANY_newline2>(\\r\\n)+)|(?P<t_java8_OPEN_BRACE>\\{)|(?P<t_java8_CLOSE_BRACE>\\})|(?P<t_ANY_BLOCK_COMMENT>/\\*(.|\\n)*?\\*/)|(?P<t_ANY_LINE_COMMENT>//.*)|(?P<t_java8_BODY>[^\\\'\\"\\{\\}\\r\\n\\/]+)|(?P<t_java8_FORWORD_SLASH>\\/)|(?P<t_java8_CHAR_LITERAL>\\\'([^\\\\\\n]|(\\\\.))*?\\\')|(?P<t_java8_STRING_LITERAL>\\"([^\\\\\\n]|(\\\\.))*?\\")', [None, ('t_ANY_newline', 'newline'), ('t_ANY_newline2', 'newline2'), None, ('t_java8_OPEN_BRACE', 'OPEN_BRACE'), ('t_java8_CLOSE_BRACE', 'CLOSE_BRACE'), ('t_ANY_BLOCK_COMMENT', 'BLOCK_COMMENT'), None, ('t_ANY_LINE_COMMENT', 'LINE_COMMENT'), ('t_java8_BODY', 'BODY'), ('t_java8_FORWORD_SLASH', 'FORWORD_SLASH'), ('t_java8_CHAR_LITERAL', 'CHAR_LITERAL'), None, None, ('t_java8_STRING_LITERAL', 'STRING_LITERAL')])]}
_lexstateignore = {'INITIAL': ' \t\x0c', 'java8': ' \t\x0c'}
_lexstateerrorf = {'INITIAL': 't_ANY_error', 'java8': 't_ANY_error'}
_lexstateeoff = {}
