
# gencmd_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1E0349E66FEF050B98C84274B5005B31'
    
_lr_action_items = {'QSTRING':([0,9,17,18,21,],[7,7,7,7,7,]),'STRING':([0,9,17,18,21,],[2,2,2,2,2,]),'NEWLINE':([1,2,3,5,6,7,8,10,11,13,14,15,17,19,20,22,23,25,],[9,-11,-3,-4,-2,-12,-19,-7,-8,-9,-10,18,-13,-14,-18,-17,-16,-15,]),'SEPERATER':([17,],[21,]),'$end':([4,9,12,16,18,24,],[0,-20,-1,-6,-20,-5,]),'PARAM':([0,9,17,18,21,],[8,8,8,8,8,]),'OPTIONNAME':([9,18,],[17,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'executable':([0,],[1,]),'optionarg':([17,21,],[19,25,]),'arg':([9,18,],[15,15,]),'option':([9,18,],[10,10,]),'string':([0,9,17,18,21,],[3,11,20,11,20,]),'command':([0,],[4,]),'args':([9,18,],[12,24,]),'quotedstring':([0,9,17,18,21,],[5,13,22,13,22,]),'param':([0,9,17,18,21,],[6,14,23,14,23,]),'empty':([9,18,],[16,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> executable NEWLINE args','command',3,'p_command','gencmd.py',66),
  ('executable -> param','executable',1,'p_executable','gencmd.py',70),
  ('executable -> string','executable',1,'p_executable','gencmd.py',71),
  ('executable -> quotedstring','executable',1,'p_executable','gencmd.py',72),
  ('args -> arg NEWLINE args','args',3,'p_args','gencmd.py',77),
  ('args -> empty','args',1,'p_args_empty','gencmd.py',81),
  ('arg -> option','arg',1,'p_arg','gencmd.py',85),
  ('arg -> string','arg',1,'p_arg','gencmd.py',86),
  ('arg -> quotedstring','arg',1,'p_arg','gencmd.py',87),
  ('arg -> param','arg',1,'p_arg','gencmd.py',88),
  ('string -> STRING','string',1,'p_string','gencmd.py',93),
  ('quotedstring -> QSTRING','quotedstring',1,'p_quotedstring','gencmd.py',97),
  ('option -> OPTIONNAME','option',1,'p_option','gencmd.py',101),
  ('option -> OPTIONNAME optionarg','option',2,'p_option_value','gencmd.py',105),
  ('option -> OPTIONNAME SEPERATER optionarg','option',3,'p_option_sep_value','gencmd.py',109),
  ('optionarg -> param','optionarg',1,'p_optionarg','gencmd.py',113),
  ('optionarg -> quotedstring','optionarg',1,'p_optionarg','gencmd.py',114),
  ('optionarg -> string','optionarg',1,'p_optionarg','gencmd.py',115),
  ('param -> PARAM','param',1,'p_param','gencmd.py',120),
  ('empty -> <empty>','empty',0,'p_empty','gencmd.py',125),
]
